***
---
# __Table of Contents__

> ## __Importing Data__
> * From a Webpage

> ## __Common HTML Import Customizations__
> 1. `storage_options` Parameter
> 2. `match` Parameter
> 3. `header` Parameter
> 4. `index_col` Parameter
> 5. `skiprows` Parameter
> 6. `decimal` Parameter
> 7. `thousands` Parameter
> 8. `parse_dates` Parameter
> 9. `keep_default_na` Parameter
> 10. `na_values` Parameter
---
***

In [1]:
import pandas as pd
import requests

## __Importing Data__
---

### Importing Data From a Webpage
The `pandas.read_html()` function parses HTML strings, files, or URLs to look for `<table>` tags and automatically extracts them into a list of pandas `DataFrame` objects. 

`read_html()` requires underlying parsing engines. Install them via your terminal. `pip install lxml html5lib beautifulsoup4`

#### Image:
![Image of a Webpage](../data/images/html-page.png)

In [2]:
# Basic Import

# This is a w3schools page with data tables
url = "https://www.w3schools.com/html/html_tables.asp"

# Read all tables into a list
tables = pd.read_html(url)

# Grab the very table from that list using their indexs
df = tables[0]
df.head()

                        Company          Contact  Country
0           Alfreds Futterkiste     Maria Anders  Germany
1    Centro comercial Moctezuma  Francisco Chang   Mexico
2                  Ernst Handel    Roland Mendel  Austria
3                Island Trading    Helen Bennett       UK
4  Laughing Bacchus Winecellars  Yoshi Tannamuri   Canada

## __Common HTML Import Customizations__
---

### 1. `storage_options` Parameter
The `storage_options` parameter accepts a dictionary of connection configurations to pass connection-specific arguments—like custom HTTP headers, authentication tokens, or cloud storage credentials—when reading an HTML file from a remote URL.

In [3]:
# 1.1 Adding HTTP Headers (Bypassing Scrapers Blocks)

## Websites often block default Python scripts to prevent web scraping and give `HTTPError: HTTP Error 403: Forbidden` error.
## You need to trick those websites into thinking your Python script is a normal web browser (like Chrome or Firefox).

url = "https://www.worldometers.info/world-population/population-by-country/"

# Specifying a standard web browser user-agent string
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
}

# Passing the headers via storage_options
tables = pd.read_html(url, storage_options=headers)

df = tables[0]
df.head()

,#,Country (or dependency),Population 2026,Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,1,India,1476625576,0.87%,12760051,497,2973190,"−440,456",1.93,29.2,37.6%,17.79%
1,2,China,1412914089,−0.22%,"−3,182,005",150,9388211,"−232,107",1.03,40.6,68.7%,17.02%
2,3,United States,349035494,0.51%,1759687,38,9147420,1177848,1.63,38.7,83.1%,4.20%
3,4,Indonesia,287886782,0.76%,2165546,159,1811570,"−39,472",2.08,30.7,60.3%,3.47%
4,5,Pakistan,259299791,1.6%,4080237,336,770880,"−1,144,738",3.44,20.8,34.7%,3.12%

### 2. `match` Parameter
The `match` parameter filters the extracted HTML tables and only returns those containing specific text or matching a regular expression. 

By default, `read_html()` parses every single table on a webpage, which can return dozens of unwanted DataFrames. The match argument acts as a precise filter to fetch exactly what you need.

#### Image:
![Image of a Webpage](../data/images/read-html-match1.png)

In [4]:
# 2.1 Matching a Simple String
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
}

url = "https://en.wikipedia.org/wiki/Minnesota"

## This only grabs tables containing the exact header text
tables = pd.read_html(url, storage_options=headers, match="Average daily maximum and minimum temperatures for selected cities in Minnesota")

## Even with 'match', a list is returned. Use [0] to grab the first matching DataFrame.
target_df = tables[0]

print(f"Found {len(tables)} table(s) matching the pattern.")
target_df.head()

Found 1 table(s) matching the pattern.

      Location July (°F) July (°C) January (°F) January (°C)
0  Minneapolis     83/64     28/18         23/7       −4/−13
1   Saint Paul     83/63     28/17         23/6       −5/−14
2    Rochester     82/63     28/17         23/3       −5/−16
3       Duluth     76/55     24/13         19/1       −7/−17
4    St. Cloud     81/58     27/14        18/−1       −7/−18

#### Images:
![Image of a Webpage](../data/images/read-html-match2.png)
![Image of a Webpage](../data/images/read-html-match3.png)

In [5]:
# 2.2 Using Regular Expressions (RegEx)
import re
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
}

url = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"

# Match tables that mention "GDP" and "country" while ignoring case sensitivity
regex_pattern = re.compile(r"gdp.*(country|region)", re.IGNORECASE)
tables = pd.read_html(url, storage_options=headers, match=regex_pattern)

target_df1 = tables[0]
target_df2 = tables[1]

print(f"Found {len(tables)} table(s) matching the pattern.")
target_df1.head()

Found 2 table(s) matching the pattern.

,Country/Territory,IMF (2026)[1],World Bank (2025)[6],United Nations (2024)[7]
0,World,126295331,118350166,100834796
1,United States,32383920,30769700,29298000
2,China[n 1],20851593,19498039,18743802
3,Germany,5452858,5050923,4659929
4,Japan,4379253,4435163,4026211

In [6]:
target_df2.head()

,Regional groupings,IMF (2026)[1],World Bank (2024)[9]
0,World,126295331.0,110983000
1,Advanced Economies/High Income[r 1],73813712.0,"71,321,000 [r 2]"
2,G7[r 3],55322424.0,-
3,Emerging Market and Developing Economies[r 4],52481610.0,-
4,Emerging and Developing Asia[r 5],29611563.0,"22,261,000 [r 6]"

### 3. `header` Parameter
The syntax for this parameter is identical to `read_csv`. However, they work differently behind the scenes because HTML files use web page code (markup tags) to create tables, while CSVs are just raw plain text.

To save time, I skipped the detailed explanation here. You can check the `importing_csv_data` notebook under the `2. header Parameter` section if you need it.

### 4. `index_col` Parameter
The syntax for this parameter is identical to `read_csv`. However, they work differently behind the scenes because HTML files use web page code (markup tags) to create tables, while CSVs are just raw plain text.

To save time, I skipped the detailed explanation here. You can check the `importing_csv_data` notebook under the `4. index_col Parameter` section if you need it.

### 5. `skiprows` Parameter
The syntax for this parameter is identical to `read_csv`. However, they work differently behind the scenes because HTML files use web page code (markup tags) to create tables, while CSVs are just raw plain text.

To save time, I skipped the detailed explanation here. You can check the `importing_csv_data` notebook under the `5. skiprows Parameter` section if you need it.

### 6. `decimal` Parameter
The syntax for this parameter is identical to `read_csv`. However, they work differently behind the scenes because HTML files use web page code (markup tags) to create tables, while CSVs are just raw plain text.

To save time, I skipped the detailed explanation here. You can check the `importing_csv_data` notebook under the `16. decimal Parameter` section if you need it.

### 7. `thousands` Parameter
The syntax for this parameter is identical to `read_csv`. However, they work differently behind the scenes because HTML files use web page code (markup tags) to create tables, while CSVs are just raw plain text.

To save time, I skipped the detailed explanation here. You can check the `importing_csv_data` notebook under the `17. thousands Parameter` section if you need it.

### 8. `parse_dates` Parameter
The syntax for this parameter is identical to `read_csv`. However, they work differently behind the scenes because HTML files use web page code (markup tags) to create tables, while CSVs are just raw plain text.

To save time, I skipped the detailed explanation here. You can check the `importing_csv_data` notebook under the `10. parse_dates Parameter` section if you need it.

### 9. `Keep_default_na` Parameter
The syntax for this parameter is identical to `read_csv`. However, they work differently behind the scenes because HTML files use web page code (markup tags) to create tables, while CSVs are just raw plain text.

To save time, I skipped the detailed explanation here. You can check the `importing_csv_data` notebook under the `13. keep_default_na Parameter` section if you need it.

### 10. `na_values` Parameter
The syntax for this parameter is identical to `read_csv`. However, they work differently behind the scenes because HTML files use web page code (markup tags) to create tables, while CSVs are just raw plain text.

To save time, I skipped the detailed explanation here. You can check the `importing_csv_data` notebook under the `14. na_values Parameter` section if you need it.